export const SITE_NAME = 'TCN Comply Malta'
export const SITE_CONTACT_EMAIL = 'contact@tcncomply.mt'
export const SITE_CONTACT_PHONE = '+356 0000 0000'
export const SITE_CONTACT_LOCATION = 'Malta'
export const SITE_SUPPORT_TAGLINE = 'Compliance operations platform for Maltese employers'
